# SPDX-FileCopyrightText: 2021 Max Reznik <reznikmm@gmail.com>
#
# SPDX-License-Identifier: MIT

on: [push]
name: Build
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and check
    steps:
      - uses: actions/checkout@v2
        with:
          path: gps-tracker
      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@v1.1
        with:
          args: --root gps-tracker lint
# Nothing to build yet
#      - name: Build RPM
#        uses: reznikmm/fedora-ada-action@v3
#        with:
#          spec: gps-tracker/.copr/gps-tracker.spec
